let theData = [{"rank":1,"team":"Mariners","park":"T-Mobile Park","top":10,"avg":10,"get":10,"total":10.0},
{"rank":2,"team":"Padres","park":"Petco Park","top":10,"avg":10,"get":10,"total":10.0},
{"rank":3,"team":"Giants","park":"Oracle Park","top":10,"avg":9,"get":9,"total":9.3},
{"rank":4,"team":"White Sox","park":"Guaranteed Rate Field","top":9,"avg":9,"get":9,"total":9.0},
{"rank":5,"team":"Royals","park":"Kauffman Stadium","top":8,"avg":8,"get":9,"total":8.3},
{"rank":6,"team":"Indians","park":"Progressive Field","top":9,"avg":8,"get":8,"total":8.3},
{"rank":7,"team":"Twins","park":"Target Field","top":9,"avg":8,"get":7,"total":8.0},
{"rank":8,"team":"Reds","park":"Great American Ball Park","top":8,"avg":8,"get":7,"total":7.7},
{"rank":9,"team":"Rays","park":"Tropicana Field","top":8,"avg":8,"get":7,"total":7.7},
{"rank":10,"team":"Brewers","park":"Miller Park","top":8,"avg":7,"get":7,"total":7.3},
{"rank":11,"team":"Tigers","park":"Comerica Park","top":9,"avg":7,"get":6,"total":7.3},
{"rank":12,"team":"Astros","park":"Minute Maid Park","top":8,"avg":6,"get":6,"total":6.7},
{"rank":13,"team":"Athletics","park":"Oakland Coliseum","top":8,"avg":6,"get":5,"total":6.3},
{"rank":14,"team":"Mets","park":"Citi Field","top":8,"avg":6,"get":5,"total":6.3},
{"rank":15,"team":"Braves","park":"Truist Park","top":7,"avg":6,"get":6,"total":6.3},
{"rank":16,"team":"Nationals","park":"Nationals Park","top":7,"avg":6,"get":6,"total":6.3},
{"rank":17,"team":"Cardinals","park":"Busch Stadium","top":7,"avg":6,"get":5,"total":6.0},
{"rank":18,"team":"Orioles","park":"Camden Yards","top":7,"avg":6,"get":5,"total":6.0},
{"rank":19,"team":"Pirates","park":"PNC Park","top":7,"avg":5,"get":5,"total":5.7},
{"rank":20,"team":"Phillies","park":"Citizen's Bank Park","top":7,"avg":5,"get":5,"total":5.7},
{"rank":21,"team":"Angels","park":"Angel Stadium","top":6,"avg":5,"get":5,"total":5.3},
{"rank":22,"team":"Rockies","park":"Coors Field","top":5,"avg":5,"get":6,"total":5.3},
{"rank":23,"team":"Cubs","park":"Wrigley Field","top":7,"avg":5,"get":4,"total":5.3},
{"rank":24,"team":"Diamondbacks","park":"Chase Field","top":5,"avg":5,"get":3,"total":4.3},
{"rank":25,"team":"Red Sox","park":"Fenway Park","top":6,"avg":4,"get":3,"total":4.3},
{"rank":26,"team":"Marlins","park":"Marlins Park","top":4,"avg":4,"get":4,"total":4.0},
{"rank":27,"team":"Dodgers","park":"Dodger Stadium","top":5,"avg":4,"get":3,"total":4.0},
{"rank":28,"team":"Yankees","park":"Yankee Stadium","top":4,"avg":4,"get":2,"total":3.3},
{"rank":29,"team":"Blue Jays","park":"Rogers Centre","top":3,"avg":3,"get":3,"total":3.0},
{"rank":30,"team":"Rangers","park":"Globe Life Field","top":"-","avg":"-","get":"-","total":"-"}]